#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

source "$DIR/../lib/ask-utils.sh"

question="${1}"
if ! googleRequest "${question}" ; then
    localRequest "${question}"
fi
